Update .bash/bashrc

diff --git a/home/dot_bash/bashrc.tmpl b/home/dot_bash/bashrc.tmpl
--- a/home/dot_bash/bashrc.tmpl
+++ b/home/dot_bash/bashrc.tmpl
@@ -121,8 +121,8 @@ fi
 export PATH="$HOME/.local/bin:$PATH"
 {{ if not .ephemeral -}}
 
-export OP_SERVICE_ACCOUNT_TOKEN="$(timeout -k 2s 5s powershell.exe -Command 'echo $env:OP_SERVICE_ACCOUNT_TOKEN' 2>/dev/null | tr -d '\r')"
-[ -z "$OP_SERVICE_ACCOUNT_TOKEN" ] && echo "warning: OP_SERVICE_ACCOUNT_TOKEN fetch timed out or failed" >&2
+# export OP_SERVICE_ACCOUNT_TOKEN="$(timeout -k 2s 5s powershell.exe -Command 'echo $env:OP_SERVICE_ACCOUNT_TOKEN' 2>/dev/null | tr -d '\r')"
+# [ -z "$OP_SERVICE_ACCOUNT_TOKEN" ] && echo "warning: OP_SERVICE_ACCOUNT_TOKEN fetch timed out or failed" >&2
 
 export GITHUB_TOKEN="$(timeout -k 2s 5s powershell.exe -Command 'echo $env:GITHUB_TOKEN' 2>/dev/null | tr -d '\r')"
 [ -z "$GITHUB_TOKEN" ] && echo "warning: GITHUB_TOKEN fetch timed out or failed" >&2
